# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Shallow Memory · Blog"
weight = 2
[zh-cn]
languageName = "中文"
title = "浅忆·Blog"
weight = 1
